{
 "title": "Threat Detection",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Fast Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"suricata\", source=\"fast-log\"}"
    }
   ]
  },
  {
   "title": "Threats by Time Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time({job=\"suricata\", filename=\"/var/log/suricata/fast.log\"} [1h])"
    }
   ]
  },
  {
   "title": "Threat Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time(\r\n  {job=\"suricata\",source=\"fast-log\"} \r\n  | regexp \"(?P<attack_type>SQL Injection|XSS Attack|Brute Force|RCE|LFI)\"\r\n  [1d]\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Total Threats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "rate({job=\"suricata\",filename=\"/var/log/suricata/fast.log\"} [1d])"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "sum by (attack_type) (\r\n  count_over_time(\r\n    {job=\"suricata\", filename=\"/var/log/suricata/fast.log\"} \r\n    | regexp \"(?P<attack_type>SQL Injection|XSS Attack|Brute Force|RCE|LFI)\"\r\n    [1h]\r\n  )\r\n)"
    }
   ]
  }
 ]
}