server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: suricata-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: suricata
          source: fast-log
    # Perbaiki posisi __path__
    relabel_configs:
      - source_labels: [__path__]
        target_label: __path__
        replacement: /var/log/suricata/fast.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{2}/\d{2}/\d{4}-\d{2}:\d{2}:\d{2}\.\d{6})\s+\[\*\*\]\s+\[(?P<sid>\d+):(?P<rev>\d+)\]\s+(?P<message>.*?)\s+\[\*\*\]\s+\[Classification:\s+(?P<classification>.*?)\]\s+\[Priority:\s+(?P<priority>\d+)\]\s+{(?P<protocol>\w+)}\s+(?P<src_ip>[\d\.]+):(?P<src_port>\d+)\s+\-\>\s+(?P<dest_ip>[\d\.]+):(?P<dest_port>\d+)'
      - labels:
          timestamp:
          sid:
          rev:
          message:
          classification:
          priority:
          protocol:
          src_ip:
          src_port:
          dest_ip:
          dest_port:

  - job_name: suricata-eve
    static_configs:
      - targets:
          - localhost
        labels:
          job: suricata
          source: eve-json
    # Perbaiki posisi __path__
    relabel_configs:
      - source_labels: [__path__]
        target_label: __path__
        replacement: /var/log/suricata/eve.json

    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            event_type: event_type
            src_ip: src_ip
            dest_ip: dest_ip
            proto: proto

#  {job="suricata", source="fast-log"}